const PREFER_COIN_MARKET = Object.freeze({
  BITCOIN: "KRW-BTC",
  ETHEREUM: "KRW-ETH",
  RIPPLE: "KRW-XRP",
  FIRMACHAIN: "KRW-FCT2",
  DOGE: "KRW-DOGE",
  ARK: "KRW-ARK",
  STELALUMEN: "KRW-XLM"
});

export { PREFER_COIN_MARKET };
