const MILLISECONDS = 1000;
const MINUTE = 60 * MILLISECONDS;

const TRADING_PERIOD = (MINUTE * MILLISECONDS) / 2;

const TRADING_SYSTEM_MAX_RECOVERY = 5;
const TRADING_SYSTEM_RECOVERY_PERIOD = MINUTE * MILLISECONDS;

const COIN_PRICE_CHANGE_DIRECTION = Object.freeze({
  UP: "UP",
  DOWN: "DOWN",
  EVEN: "EVEN",
});

const ORDER_PRICE_TYPE = Object.freeze({
  LIMIT: "limit",
  PRICE: "price",
  MARKET: "market",
});

const ORDER_TYPE = Object.freeze({
  BID: "bid",
  ASK: "ask",
});

const MOVING_AVERAGE_MINUTE = Object.freeze({
  FIVE: 5,
  TWENTY: 20,
  SIXTY: 60,
});

const TICKER_REQUEST_TIMING = 10 * MILLISECONDS;

export {
  TRADING_PERIOD,
  TRADING_SYSTEM_MAX_RECOVERY,
  TRADING_SYSTEM_RECOVERY_PERIOD,
  COIN_PRICE_CHANGE_DIRECTION,
  ORDER_PRICE_TYPE,
  ORDER_TYPE,
  MOVING_AVERAGE_MINUTE,
  TICKER_REQUEST_TIMING,
  MILLISECONDS,
};
